---
- name: Pull Docker image from Docker Hub
  hosts: localhost
  remote_user: SPE
  become: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "asmita963/calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Start Docker service
      service:
        name: docker
        state: started
    - name: Remove existing containers if running
      shell: docker rm -f calculator

    - name: Running container
      shell: docker run -it -d --name calculator asmita963/calculator
